#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=feet;size=50", "id=cyclic_player;size=50", "id=hands;size=50", "id=ring;size=100", "id=belt;size=50", "id=back;size=50", "id=necklace;size=50", "id=bracelet;size=50", "id=quiver;size=50", "id=body;size=50", "id=curio;size=50", "id=head;size=50", "id=slots;size=50", "id=charm;size=50"]

