
[Compatibility]

	[Compatibility.vampirism]
		enable_compat_vampirism = true
		disable_integrations_version_check = false

	[Compatibility.biomesoplenty]
		enable_compat_biomesoplenty = true
		#Whether sundamage should be applied to vampires in this biome or not
		disable_sundamage_ominous_woods = true

	[Compatibility.toughasnails]
		enable_compat_toughasnails = true
		#Limit thirst for vampires
		disableThirst = true

	[Compatibility.guardvillagers]
		enable_compat_guardvillagers = true

