
#Client settings
[client]

	#Tooltips
	[client.tooltips]
		#Should the mod change the color of tooltips?
		coloredTooltips = true
		#Should hunter food tooltips and tooltip's color be shown to all fractions? (Only shown to vampires by default)
		hunterTooltipsForEveryone = false

	#AppleSkin
	[client.appleskin]
		#Should AppleSkin tooltips' food values be fixed depending on player's race? (In case the player is a vampire, it'll show blood values for vampire food)
		correctAppleSkinTooltips = true
		#Should AppleSkin tooltips be hidden for human food if the player is a vampire?
		hideAppleSkinHumanFoodTooltipsForVampires = true

